---
- hosts: all
  become: yes

  tasks:
  - name: upgrade all packages
    yum: name=* state=latest 
    
  - name: Install dependecies
    yum:
      name: "{{item}}"
      state: present
    with_items:
      - java-11-openjdk-devel
      - tomcat
      - tomcat-webapps 
      - tomcat-admin-webapps 
      - tomcat-docs-webapp 
      - tomcat-javadoc  
  
  - name: Start tomcat
    service: name=tomcat state=started enabled=yes
